[package]
name = "assignment3"
version = "0.1.0"
authors = ["Philip <philip.n@digipen.edu>"]
edition = "2018"

[lib]
name = "assignment"
path = "src/lib.rs"

[[bin]]
name = "assignment3"
path = "src/main.rs"

[dependencies]
rand = "0.6.5"
